[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "account-abstraction/=lib/account-abstraction/",
    "@account-abstraction/=lib/account-abstraction/contracts/",
    "solmate/=lib/solmate/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.rpc-endpoints]
sepolia = "https://sepolia.infura.io/v3/2WCbZ8YpmuPxUtM6PzbFOfY5k4B"